"""
Claude Enterprise Analytics API data collector.

Collects cost and usage data from the **Claude Enterprise Analytics API** -- the
claude.ai / Claude for Work usage surface (Claude chat, Claude Code, Cowork,
Office Agent, Claude in Chrome). This is DISTINCT from the Anthropic developer
Admin API used by ``anthropic_collector.py``: it lives under a different path
(``/v1/organizations/analytics``), uses GET endpoints with query params, and
requires an API key with the ``read:analytics`` scope generated by the Enterprise
organization's Primary Owner.

Assumed response schema (verified against the Claude Enterprise Analytics API
reference guide -- see docstrings on the fetch methods for the per-endpoint
shape):

Top level::

    {
        "organization_id": "...",
        "data": [ <bucket>, ... ],
        "has_more": false,
        "next_page": "<opaque cursor or null>",
        "data_refreshed_at": "2026-06-24T00:00:00Z"
    }

Each ``bucket``::

    {
        "starting_at": "2026-06-23T00:00:00Z",
        "ending_at": "2026-06-24T00:00:00Z",
        "results": [ <result>, ... ]
    }

Each cost ``result`` (cost_report) includes the usage dimension/token fields
plus::

    {
        "model": "claude-...",          # null unless grouped by model
        "product": "claude_code",       # null unless grouped by product
        "cost_type": "tokens",          # null unless grouped by cost_type
        "token_type": "...",            # null unless grouped by token_type
        "currency": "USD",
        "amount": 12345,                # DISCOUNTED cost in fractional cents
        "list_amount": 23456            # LIST-price cost in fractional cents
    }

Each usage ``result`` (usage_report) includes::

    {
        "model": "claude-...",
        "product": "claude_code",
        "uncached_input_tokens": 100,
        "cache_creation.ephemeral_5m_input_tokens": 0,
        "cache_creation.ephemeral_1h_input_tokens": 0,
        "cache_read_input_tokens": 50,
        "output_tokens": 25,
        "server_tool_use.web_search_requests": 0
    }

NOTE: ``amount`` / ``list_amount`` are documented as *fractional cents*; this
collector divides by 100 to produce USD. If live data shows the values are
already in dollars this constant (``CENTS_PER_USD``) must be revisited.
"""

import asyncio
from datetime import datetime, timedelta, timezone
from typing import Dict, List, Any, Optional
import logging
import httpx

from app.collectors.base import BaseCollector

logger = logging.getLogger(__name__)


class ClaudeAIAnalyticsCollector(BaseCollector):
    """
    Collector for the Claude Enterprise Analytics API.

    Uses the following endpoints (HTTP GET, query-param driven):
    - GET /cost_report   -> USD cost over time
    - GET /usage_report  -> token counts over time

    Features:
    - Exponential-backoff retry on 429 / 5xx (mirrors AnthropicCollector)
    - Cursor pagination via ``has_more`` + ``next_page``
    - Backfill chunked into <=31-day spans (the API max span per request)
    - Defensive parsing -- skips unparseable buckets/results
    """

    ANALYTICS_API_BASE_URL = "https://api.anthropic.com/v1/organizations/analytics"
    ANTHROPIC_VERSION = "2023-06-01"
    MAX_RETRIES = 3
    INITIAL_BACKOFF = 2  # seconds
    # The Analytics API allows at most a 31-day span per request.
    MAX_SPAN_DAYS = 31
    # ``amount`` / ``list_amount`` are returned in fractional cents.
    CENTS_PER_USD = 100.0

    def __init__(
        self,
        api_key: str,
        user_id: str,
        provider_id: str,
        organization_id: Optional[str] = None,
    ):
        """
        Initialize the Claude Enterprise Analytics collector.

        Args:
            api_key: API key with the ``read:analytics`` scope.
            user_id: User ID who owns this API key.
            provider_id: Provider ID from the database.
            organization_id: Optional organization ID (recorded in metadata).
        """
        super().__init__(api_key, user_id)
        self.provider_id = provider_id
        self.organization_id = organization_id
        # No Anthropic SDK client needed -- the Analytics API is plain REST.
        self.http_client = httpx.AsyncClient(
            base_url=self.ANALYTICS_API_BASE_URL,
            headers={
                "anthropic-version": self.ANTHROPIC_VERSION,
                "x-api-key": api_key,
            },
            timeout=30.0,
        )

    @property
    def provider_name(self) -> str:
        """Return the provider name."""
        return "claude-ai"

    async def _make_request_with_retry(
        self,
        method: str,
        endpoint: str,
        params: Optional[Dict[str, Any]] = None,
        retry_count: int = 0,
    ) -> Dict[str, Any]:
        """
        Make an API request with exponential-backoff retry logic.

        Args:
            method: HTTP method (currently only GET is used).
            endpoint: API endpoint path (relative to the base URL).
            params: Query-string parameters.
            retry_count: Current retry attempt.

        Returns:
            Dict: Parsed response JSON.

        Raises:
            Exception: If all retries are exhausted.
        """
        try:
            if method == "POST":
                response = await self.http_client.post(endpoint, json=params)
            else:
                response = await self.http_client.get(endpoint, params=params)

            response.raise_for_status()
            return response.json()

        except httpx.HTTPStatusError as e:
            if e.response.status_code == 429 and retry_count < self.MAX_RETRIES:
                # Rate limit exceeded - wait and retry
                backoff_time = self.INITIAL_BACKOFF * (2 ** retry_count)
                self.logger.warning(
                    f"Rate limit hit, backing off for {backoff_time}s "
                    f"(attempt {retry_count + 1}/{self.MAX_RETRIES})"
                )
                await asyncio.sleep(backoff_time)
                return await self._make_request_with_retry(
                    method, endpoint, params, retry_count + 1
                )

            elif e.response.status_code >= 500 and retry_count < self.MAX_RETRIES:
                # Server error - retry with backoff
                backoff_time = self.INITIAL_BACKOFF * (2 ** retry_count)
                self.logger.warning(
                    f"Server error {e.response.status_code}, retrying in {backoff_time}s"
                )
                await asyncio.sleep(backoff_time)
                return await self._make_request_with_retry(
                    method, endpoint, params, retry_count + 1
                )

            else:
                self.logger.error(
                    f"API request failed: {e.response.status_code} - {e.response.text}"
                )
                raise

        except Exception as e:
            if retry_count < self.MAX_RETRIES:
                backoff_time = self.INITIAL_BACKOFF * (2 ** retry_count)
                self.logger.warning(
                    f"Request failed: {str(e)}, retrying in {backoff_time}s"
                )
                await asyncio.sleep(backoff_time)
                return await self._make_request_with_retry(
                    method, endpoint, params, retry_count + 1
                )
            raise

    async def _fetch_report(
        self,
        endpoint: str,
        start_time: datetime,
        end_time: datetime,
        bucket_width: str = "1d",
        group_by: Optional[List[str]] = None,
    ) -> List[Dict[str, Any]]:
        """
        Fetch all paginated buckets for a single report endpoint.

        Args:
            endpoint: ``/cost_report`` or ``/usage_report``.
            start_time: Start of the range (UTC, RFC3339 ``starting_at``).
            end_time: End of the range (UTC, RFC3339 ``ending_at``).
            bucket_width: One of ``1m``, ``1h``, ``1d`` (default ``1d``).
            group_by: Optional list of dimensions (e.g. ``["model"]``) passed
                as repeated ``group_by[]`` query params.

        Returns:
            A flat list of bucket dicts (each with ``starting_at`` / ``results``).
        """
        all_buckets: List[Dict[str, Any]] = []
        next_page: Optional[str] = None

        starting_at = start_time.isoformat()
        ending_at = end_time.isoformat()

        self.logger.info(
            f"Fetching {endpoint} from {starting_at} to {ending_at} "
            f"(bucket_width={bucket_width})"
        )

        while True:
            params: Dict[str, Any] = {
                "starting_at": starting_at,
                "ending_at": ending_at,
                "bucket_width": bucket_width,
            }
            if group_by:
                # httpx serialises a list value as repeated query params, which
                # matches the API's ``group_by[]`` expectation.
                params["group_by[]"] = group_by
            if next_page:
                params["page"] = next_page

            response = await self._make_request_with_retry("GET", endpoint, params=params)

            page_buckets = response.get("data", []) or []
            all_buckets.extend(page_buckets)

            self.logger.info(
                f"Retrieved {len(page_buckets)} buckets from {endpoint} "
                f"(total: {len(all_buckets)})"
            )

            if not response.get("has_more"):
                break
            next_page = response.get("next_page")
            if not next_page:
                break

        return all_buckets

    async def fetch_cost_report(
        self,
        start_time: datetime,
        end_time: datetime,
        bucket_width: str = "1d",
        group_by: Optional[List[str]] = None,
    ) -> List[Dict[str, Any]]:
        """
        Fetch the cost report (USD over time) from the Analytics API.

        Response shape (per bucket result)::

            {"model": ..., "product": ..., "cost_type": ..., "currency": "USD",
             "amount": <fractional cents>, "list_amount": <fractional cents>}
        """
        if group_by is None:
            group_by = ["model"]
        return await self._fetch_report(
            "/cost_report", start_time, end_time, bucket_width, group_by
        )

    async def fetch_usage_report(
        self,
        start_time: datetime,
        end_time: datetime,
        bucket_width: str = "1d",
        group_by: Optional[List[str]] = None,
    ) -> List[Dict[str, Any]]:
        """
        Fetch the usage report (token counts over time) from the Analytics API.

        Response shape (per bucket result)::

            {"model": ..., "uncached_input_tokens": ..., "cache_read_input_tokens": ...,
             "output_tokens": ...}
        """
        if group_by is None:
            group_by = ["model"]
        return await self._fetch_report(
            "/usage_report", start_time, end_time, bucket_width, group_by
        )

    @staticmethod
    def _result_key(starting_at: Optional[str], result: Dict[str, Any]) -> tuple:
        """Build a join key matching cost and usage results within a bucket."""
        return (
            starting_at,
            result.get("model"),
            result.get("product"),
        )

    @staticmethod
    def _sum_input_tokens(result: Dict[str, Any]) -> Optional[int]:
        """
        Sum all input-token flavours present in a usage result.

        Covers ``input_tokens``, ``uncached_input_tokens``,
        ``cache_read_input_tokens`` and the dotted cache-creation fields. Returns
        ``None`` if no input-token field is present at all.
        """
        input_field_names = [
            "input_tokens",
            "uncached_input_tokens",
            "cache_read_input_tokens",
            "cache_creation.ephemeral_5m_input_tokens",
            "cache_creation.ephemeral_1h_input_tokens",
        ]
        total = 0
        found = False
        for name in input_field_names:
            value = result.get(name)
            if value is not None:
                try:
                    total += int(value)
                    found = True
                except (TypeError, ValueError):
                    continue
        return total if found else None

    @staticmethod
    def _safe_int(value: Any) -> Optional[int]:
        """Coerce to int, returning None on failure or missing value."""
        if value is None:
            return None
        try:
            return int(value)
        except (TypeError, ValueError):
            return None

    def transform_to_cost_records(
        self,
        cost_buckets: List[Dict[str, Any]],
        usage_buckets: List[Dict[str, Any]],
        bucket_width: str = "1d",
    ) -> List[Dict[str, Any]]:
        """
        Transform Analytics API cost + usage buckets into cost_records rows.

        Cost is the source of truth for emitted rows (one record per cost
        result); usage results are joined in by (bucket start, model, product)
        to attach token counts. Defensive throughout: unparseable buckets and
        results are skipped rather than raising.

        Args:
            cost_buckets: Buckets from ``fetch_cost_report``.
            usage_buckets: Buckets from ``fetch_usage_report``.
            bucket_width: Bucket width used for the request (recorded in metadata).

        Returns:
            List of records matching the cost_records DB schema.
        """
        # Build a lookup of usage results keyed by (start, model, product).
        usage_map: Dict[tuple, Dict[str, Any]] = {}
        for bucket in usage_buckets or []:
            if not isinstance(bucket, dict):
                continue
            starting_at = bucket.get("starting_at")
            for result in bucket.get("results", []) or []:
                if not isinstance(result, dict):
                    continue
                usage_map[self._result_key(starting_at, result)] = result

        transformed_records: List[Dict[str, Any]] = []

        for bucket in cost_buckets or []:
            if not isinstance(bucket, dict):
                continue
            starting_at = bucket.get("starting_at")
            if not starting_at:
                self.logger.warning("Skipping cost bucket with no starting_at")
                continue

            # Parse the bucket start timestamp once.
            try:
                timestamp = datetime.fromisoformat(
                    str(starting_at).replace("Z", "+00:00")
                )
                # Guarantee tz-awareness.
                if timestamp.tzinfo is None:
                    timestamp = timestamp.replace(tzinfo=timezone.utc)
                timestamp_iso = timestamp.isoformat()
            except Exception as e:  # noqa: BLE001 - defensive parsing
                self.logger.warning(f"Failed to parse bucket start {starting_at}: {e}")
                continue

            for result in bucket.get("results", []) or []:
                if not isinstance(result, dict):
                    continue

                # Cost: ``amount`` is discounted, in fractional cents -> USD.
                raw_amount = result.get("amount")
                try:
                    cost_usd = (
                        float(raw_amount) / self.CENTS_PER_USD
                        if raw_amount is not None
                        else 0.0
                    )
                except (TypeError, ValueError):
                    self.logger.warning(
                        f"Unparseable cost amount {raw_amount!r} in bucket "
                        f"{starting_at}; defaulting to 0.0"
                    )
                    cost_usd = 0.0

                raw_list_amount = result.get("list_amount")
                try:
                    list_amount_usd = (
                        float(raw_list_amount) / self.CENTS_PER_USD
                        if raw_list_amount is not None
                        else None
                    )
                except (TypeError, ValueError):
                    list_amount_usd = None

                # model_name must NEVER be null.
                model_name = result.get("model") or "claude-ai"

                # Join usage by (start, model, product).
                usage = usage_map.get(self._result_key(starting_at, result), {})

                input_tokens = self._sum_input_tokens(usage)
                output_tokens = self._safe_int(usage.get("output_tokens"))

                if input_tokens is None and output_tokens is None:
                    tokens_used: Optional[int] = None
                else:
                    tokens_used = (input_tokens or 0) + (output_tokens or 0)

                record = {
                    "user_id": self.user_id,
                    "provider_id": self.provider_id,
                    "timestamp": timestamp_iso,
                    "model_name": model_name,
                    "cost_usd": float(cost_usd),
                    "tokens_used": tokens_used,
                    "input_tokens": input_tokens,
                    "output_tokens": output_tokens,
                    "request_count": 1,
                    "collection_method": "api_automated",
                    "metadata": {
                        "provider": "claude-ai",
                        "list_amount_usd": list_amount_usd,
                        "bucket_width": bucket_width,
                        "group": {
                            "model": result.get("model"),
                            "product": result.get("product"),
                            "cost_type": result.get("cost_type"),
                        },
                        "organization_id": self.organization_id,
                    },
                }

                transformed_records.append(record)

        self.logger.info(f"Transformed {len(transformed_records)} records")
        return transformed_records

    @staticmethod
    def _iter_chunks(start_time: datetime, end_time: datetime, max_days: int):
        """Yield (chunk_start, chunk_end) spans no longer than ``max_days``."""
        chunk_start = start_time
        max_delta = timedelta(days=max_days)
        while chunk_start < end_time:
            chunk_end = min(chunk_start + max_delta, end_time)
            yield chunk_start, chunk_end
            chunk_start = chunk_end

    async def collect_data(
        self,
        start_time: Optional[datetime] = None,
        end_time: Optional[datetime] = None,
        backfill: bool = False,
    ) -> List[Dict[str, Any]]:
        """
        Collect cost + usage data from the Claude Enterprise Analytics API.

        Requests are chunked into <=31-day spans (the API's per-request max).

        Args:
            start_time: Start of collection (defaults to 24h ago, or 90d for backfill).
            end_time: End of collection (defaults to now).
            backfill: If True, default the window to the last 90 days.

        Returns:
            List of cost records ready for database insertion.
        """
        if end_time is None:
            end_time = datetime.now(timezone.utc)

        if start_time is None:
            if backfill:
                start_time = end_time - timedelta(days=90)
                self.logger.info("Backfill mode: collecting last 90 days of data")
            else:
                start_time = end_time - timedelta(hours=24)

        bucket_width = "1d"
        all_records: List[Dict[str, Any]] = []

        try:
            for chunk_start, chunk_end in self._iter_chunks(
                start_time, end_time, self.MAX_SPAN_DAYS
            ):
                cost_task = self.fetch_cost_report(
                    chunk_start, chunk_end, bucket_width=bucket_width
                )
                usage_task = self.fetch_usage_report(
                    chunk_start, chunk_end, bucket_width=bucket_width
                )
                cost_buckets, usage_buckets = await asyncio.gather(
                    cost_task, usage_task
                )

                records = self.transform_to_cost_records(
                    cost_buckets, usage_buckets, bucket_width=bucket_width
                )
                all_records.extend(records)

            self.logger.info(
                f"Successfully collected {len(all_records)} records from "
                f"Claude Analytics API "
                f"({start_time.isoformat()} to {end_time.isoformat()})"
            )

            return all_records

        except Exception as e:
            self.logger.error(f"Failed to collect Claude Analytics data: {str(e)}")
            raise

    async def backfill_historical_data(self, days: int = 90) -> Dict[str, Any]:
        """
        Backfill historical data from the Claude Enterprise Analytics API.

        Args:
            days: Number of days to backfill.

        Returns:
            Summary of the backfill operation.
        """
        end_time = datetime.now(timezone.utc)
        start_time = end_time - timedelta(days=days)

        self.logger.info(
            f"Starting backfill for {days} days of Claude Analytics data"
        )

        try:
            records = await self.collect_data(start_time, end_time, backfill=True)
            stored_count = await self.store_records(records)

            return {
                "status": "success",
                "provider": self.provider_name,
                "backfill_days": days,
                "records_collected": len(records),
                "records_stored": stored_count,
                "start_time": start_time.isoformat(),
                "end_time": end_time.isoformat(),
            }

        except Exception as e:
            self.logger.error(f"Backfill failed: {str(e)}")
            return {
                "status": "error",
                "provider": self.provider_name,
                "error": str(e),
            }

    async def close(self):
        """Close HTTP client connection."""
        await self.http_client.aclose()

    async def __aenter__(self):
        """Async context manager entry."""
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        """Async context manager exit."""
        await self.close()
